// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTvA0DDc_jn9K8qMFeWAaHEkpeFacolbs',
    appId: '1:858501899685:web:809411e491574b5da9b44c',
    messagingSenderId: '858501899685',
    projectId: 'rainguard-13ec1',
    authDomain: 'rainguard-13ec1.firebaseapp.com',
    storageBucket: 'rainguard-13ec1.firebasestorage.app',
    measurementId: 'G-QVW616VSZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMcuSYdXzLNKBEfGcOy_Gpy7ijC7qmkmk',
    appId: '1:858501899685:android:a1f5e18a6820e460a9b44c',
    messagingSenderId: '858501899685',
    projectId: 'rainguard-13ec1',
    storageBucket: 'rainguard-13ec1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5QOFWdkAT2mWgQcyLn6oIFf6btVAUsv8',
    appId: '1:858501899685:ios:5c7dc5c60f754b36a9b44c',
    messagingSenderId: '858501899685',
    projectId: 'rainguard-13ec1',
    storageBucket: 'rainguard-13ec1.firebasestorage.app',
    iosBundleId: 'com.example.rainguardApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5QOFWdkAT2mWgQcyLn6oIFf6btVAUsv8',
    appId: '1:858501899685:ios:5c7dc5c60f754b36a9b44c',
    messagingSenderId: '858501899685',
    projectId: 'rainguard-13ec1',
    storageBucket: 'rainguard-13ec1.firebasestorage.app',
    iosBundleId: 'com.example.rainguardApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTvA0DDc_jn9K8qMFeWAaHEkpeFacolbs',
    appId: '1:858501899685:web:9eb71fce443595dea9b44c',
    messagingSenderId: '858501899685',
    projectId: 'rainguard-13ec1',
    authDomain: 'rainguard-13ec1.firebaseapp.com',
    storageBucket: 'rainguard-13ec1.firebasestorage.app',
    measurementId: 'G-K81VN528LW',
  );
}
